packages:
  - apps/*
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  maplibre-gl: true
  sharp: true
  simple-git-hooks: true
  vue-demi: true
  workerd: true
